### ISSUE TITLE
Failed to build DependencyGraph Issue

### ISSUE THREAD

**Issue by jojonarte** [alcat2008/react-native-auto-expanding-textinput#2]
I'm getting this issue.

Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: Promise
  Paths: B:\AutoHugas\node_modules\react-native-auto-expanding-textinput\node_modules\react-native\Libraries\Promise.js collides with B:\AutoHugas\node_modules\react-native\Libraries\Promise.js

This error is caused by a @providesModule declaration with the same name accross two different files.
Error: @providesModule naming collision:
  Duplicate module name: Promise
  Paths: B:\AutoHugas\node_modules\react-native-auto-expanding-textinput\node_modules\react-native\Libraries\Promise.js collides with B:\AutoHugas\node_modules\react-native\Libraries\Promise.js

This error is caused by a @providesModule declaration with the same name accross two different files.
    at HasteMap._updateHasteMap (B:\AutoHugas\node_modules\react-native\node_modules\node-haste\lib\DependencyGraph\HasteMap.js:160:15)
    at B:\AutoHugas\node_modules\react-native\node_modules\node-haste\lib\DependencyGraph\HasteMap.js:125:25
    at run (B:\AutoHugas\node_modules\react-native\node_modules\babel-polyfill\node_modules\core-js\modules\es6.promise.js:89:22)
    at B:\AutoHugas\node_modules\react-native\node_modules\babel-polyfill\node_modules\core-js\modules\es6.promise.js:102:28
    at flush (B:\AutoHugas\node_modules\react-native\node_modules\babel-polyfill\node_modules\core-js\modules_microtask.js:18:9)
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)

**Comment by alcat2008** [comment]
@jojonarte just remove the dependencies would solve this problem.
